apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tco-demo-uploads
  namespace: tco-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tco-demo-results
  namespace: tco-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tco-demo-backend
  namespace: tco-demo
  labels:
    app: tco-demo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tco-demo-backend
  template:
    metadata:
      labels:
        app: tco-demo-backend
    spec:
      serviceAccountName: tco-demo-sa
      containers:
      - name: backend
        image: 891377073036.dkr.ecr.us-west-2.amazonaws.com/tco-demo-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: backend
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: tco-demo-secrets
              key: openai-api-key
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        - name: results
          mountPath: /app/results
        - name: blank-forms
          mountPath: /app/blank_forms
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: tco-demo-uploads
      - name: results
        persistentVolumeClaim:
          claimName: tco-demo-results
      - name: blank-forms
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tco-demo-frontend
  namespace: tco-demo
  labels:
    app: tco-demo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tco-demo-frontend
  template:
    metadata:
      labels:
        app: tco-demo-frontend
    spec:
      containers:
      - name: frontend
        image: 891377073036.dkr.ecr.us-west-2.amazonaws.com/tco-demo-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: frontend
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://tco-demo.nolancrook.com/api" 