apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tco-demo
  namespace: tco-demo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: tco-demo.nolancrook.com
    http:
      paths:
      - path: /oauth2/idpresponse
        pathType: Prefix
        backend:
          service:
            name: tco-demo-frontend
            port:
              number: 80
      # Frontend API proxy routes (handled by Next.js)
      - path: /api/(proxy|status|download|upload-process)(.*)
        pathType: Prefix
        backend:
          service:
            name: tco-demo-frontend
            port:
              number: 80
      # Direct backend API routes
      - path: /backend-api/()(.*)
        pathType: Prefix
        backend:
          service:
            name: tco-demo-backend
            port:
              number: 8001
      # All other routes go to frontend
      - path: /()(.*)
        pathType: Prefix
        backend:
          service:
            name: tco-demo-frontend
            port:
              number: 80 