apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tco-demo-external-secrets
  namespace: tco-demo
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: tco-demo-secrets
    creationPolicy: Owner
  data:
  - secretKey: openai-api-key
    remoteRef:
      key: tco-demo/openai-api-key
      property: key
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: tco-demo
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: tco-demo-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tco-demo-sa
  namespace: tco-demo
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891377073036:role/tco-demo-role 