apiVersion: v1
kind: Service
metadata:
  name: tco-demo-backend
  namespace: tco-demo
  labels:
    app: tco-demo-backend
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: backend
  selector:
    app: tco-demo-backend
---
apiVersion: v1
kind: Service
metadata:
  name: tco-demo-frontend
  namespace: tco-demo
  labels:
    app: tco-demo-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: frontend
  selector:
    app: tco-demo-frontend 