apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: efs-config
  namespace: deepseek
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: efs-config
  data:
    - secretKey: efs-id
      remoteRef:
        key: /eks/efs-id 