apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deepseek

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- service-account.yaml
- parameter-store.yaml
- secret-store.yaml
- hf-parameter.yaml
- efs.yaml