apiVersion: v1
kind: Secret
metadata:
  name: efs-config
  namespace: deepseek
type: Opaque
data:
  # This is a placeholder value that will be overwritten by External Secrets
  efs-id: ZHVtbXktZWZzLWlk # Base64 encoded "dummy-efs-id" 