apiVersion: v1
kind: ServiceAccount
metadata:
  name: deepseek-api-sa
  namespace: deepseek
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891377073036:role/eks-deepseek-headless-role
    eks.amazonaws.com/sts-regional-endpoints: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
  name: efs-csi-controller-sa
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891377073036:role/eks-efs-csi-driver-role-dev

