apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: umami-ingress
  namespace: umami
  labels:
    app: umami
  annotations:
    # NGINX Ingress Controller annotations
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - analytics.nolancrook.com  # Change this to your desired domain
  rules:
  - host: analytics.nolancrook.com  # Change this to your desired domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: umami-service
            port:
              number: 3000 

