apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Metadata
metadata:
  name: umami
  
# Resources to deploy
resources:
- namespace.yaml
- secrets.yaml
- storage-class.yaml
- storage.yaml
- postgres-deployment.yaml
- umami-deployment.yaml
- ingress.yaml
- ebs-csi-monitoring.yaml
