
apiVersion: v1
kind: ConfigMap
metadata:
  name: umami-config
  namespace: umami
data:
  POSTGRES_DB: "umami"
  POSTGRES_USER: "umami"
  DATABASE_TYPE: "postgresql"
  DISABLE_TELEMETRY: "1"
  REMOVE_TRAILING_SLASH: "1"
  NODE_ENV: "production" 

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-secrets
  namespace: umami
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: umami-secrets
    creationPolicy: Owner
  data:
  - secretKey: umami-postgres-password
    remoteRef:
      key: umami/postgres-password
      property: password
  - secretKey: umami-postgres-user
    remoteRef:
      key: umami/postgres-user
      property: user
  - secretKey: umami-password
    remoteRef:
      key: umami/password
      property: password
  - secretKey: umami-app-secret
    remoteRef:
      key: umami/app-secret
      property: secret
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: umami
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: umami-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: umami-sa
  namespace: umami
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891377073036:role/umami-role 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: aws-ebs-csi-driver
  name: ebs-csi-controller-sa
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891377073036:role/eks-ebs-csi-driver-role-dev
