apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  description: NGINX Ingress Controller Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: stable-diffusion
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*' 