apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: stable-diffusion
  namespace: argocd
spec:
  description: Stable Diffusion Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: stable-diffusion
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*' 