apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-knowledgebase-secrets
  namespace: demo-knowledgebase
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: demo-knowledgebase-secrets
    creationPolicy: Owner
  data:
  - secretKey: openai-api-key
    remoteRef:
      key: langchain/openai-api-key
      property: key
  - secretKey: knowledge-base-id
    remoteRef:
      key: rag-project-knowledge-base-id
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: demo-knowledgebase
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: demo-knowledgebase-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-knowledgebase-sa
  namespace: demo-knowledgebase
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891377073036:role/demo-knowledgebase-role 