apiVersion: apps/v1
kind: Deployment
metadata:
  name: dino-backend
  namespace: dino-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dino-backend
  template:
    metadata:
      labels:
        app: dino-backend
    spec:
      containers:
      - name: backend
        image: 891377073036.dkr.ecr.us-west-2.amazonaws.com/dino-backend:latest
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: dino-backend
  namespace: dino-runner
spec:
  selector:
    app: dino-backend
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP 