apiVersion: apps/v1
kind: Deployment
metadata:
  name: dino-game-backend
  namespace: dino-runner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dino-game-backend
  template:
    metadata:
      labels:
        app: dino-game-backend
    spec:
      containers:
      - name: dino-game-backend
        image: 891377073036.dkr.ecr.us-west-2.amazonaws.com/dino-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: PORT
          value: "3001"
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: dino-game-backend
  namespace: dino-runner
  annotations:
    # Add annotations for WebSocket support
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    # Increase timeouts for WebSockets
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
spec:
  selector:
    app: dino-game-backend
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP 