apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://github.com/nolantcrook/stable-diffusion-gitops
  server.insecure: "true"
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  server.secretkey: $argocd-secret:server.secretkey 