apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - configmap.yaml
  - service.yaml
  - deployment.yaml
  - applicationset.yaml
  - rbac.yaml

