apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.3/manifests/install.yaml
- argocd-secret.yaml

# Replace patchesStrategicMerge with patchesJson6902
patches:
- target:
    group: ""
    version: v1
    kind: ConfigMap
    name: argocd-cm
  path: patches/configmap-patch.yaml
