apiVersion: v1
kind: Secret
metadata:
  name: github-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/roguewavefunction/stable-diffusion-gitops.git
  username: ${GITHUB_USERNAME}
  password: ${GITHUB_TOKEN} 