apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: NodePort
  ports:
    - name: http
      port: 80               # Exposing the service on port 80 for HTTP
      targetPort: 8080       # Backend pod port for HTTP
      nodePort: 30080        # NodePort for HTTP
      protocol: TCP
    - name: https
      port: 443              # Exposing the service on port 443 for HTTPS
      targetPort: 8080       # Backend pod port for HTTPS
      nodePort: 30443        # NodePort for HTTPS
      protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server
