apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080  # ArgoCD server port
      protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server
