apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion-api
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2" 