apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stable-diffusion

resources:
- ../../base

patchesStrategicMerge:
- config.yaml

images:
- name: your-registry.amazonaws.com/stable-diffusion-api
  newName: your-registry.amazonaws.com/stable-diffusion-api
  newTag: latest 