apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- name: aws-config
  namespace: invokeai-api
  literals:
  - AWS_ACCOUNT_ID=891377073036

vars:
- name: AWS_ACCOUNT_ID
  objref:
    kind: ConfigMap
    name: aws-config
    apiVersion: v1
  fieldref:
    fieldpath: data.AWS_ACCOUNT_ID

patches:
- path: patches.yaml 