apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stratis

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app: stratis-frontend 