apiVersion: v1
kind: ServiceAccount
metadata:
  name: tolby-backend-sa
  namespace: tolby
  labels:
    app: tolby-backend
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891377073036:role/eks-tolby-role 