apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml    # Only include Kubernetes resources here

# Values file is only referenced in configMapGenerator
patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: argocd-server-ingress