apiVersion: apps/v1
kind: Deployment
metadata:
  name: invokeai-headless
  namespace: invokeai-headless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invokeai-headless
  template:
    metadata:
      labels:
        app: invokeai-headless
        lifecycle: "Ec2Spot"
        node.kubernetes.io/lifecycle: "spot"
        node.kubernetes.io/gpu: "true"
    spec:
      serviceAccountName: invokeai-headless-sa
      containers:
      - name: invokeai-headless
        image: 891377073036.dkr.ecr.us-west-2.amazonaws.com/invokeai-headless:latest
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      nodeSelector:
        node.kubernetes.io/gpu: "true"