apiVersion: v1
kind: Service
metadata:
  name: invokeai-headless
  namespace: invokeai-headless
spec:
  type: ClusterIP
  selector:
    app: invokeai-headless
  ports:
  - port: 5000
    targetPort: 5000