apiVersion: v1
kind: ServiceAccount
metadata:
  name: invokeai-headless-sa
  namespace: invokeai-headless
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891377073036:role/eks-invokeai-headless-role