apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hauliday

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- backend-deployment.yaml
- backend-service.yaml
- backend-serviceaccount.yaml

# commonLabels removed to allow individual resource labels 