apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  # Disable internal TLS
  server.insecure: "true"
  # Configure HTTPS redirect
  server.insecure.skip.tls.verify: "true" 