apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  server:
    insecure: false
    route:
      enabled: true
    service:
      type: LoadBalancer
  
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
  
  repo:
    mountsafetoroot: true
  
  dex:
    openShiftOAuth: false
  
  ha:
    enabled: false 