apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
    - name: https
      port: 8080
      targetPort: 8080
      nodePort: 30443
      protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server 