apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-core
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  # Ensures clean deletion
spec:
  project: default
  source:
    repoURL: https://github.com/roguewavefunction/stable-diffusion-gitops.git
    targetRevision: HEAD
    path: argocd/install/core
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true  # Important for updating CRDs and other resources 