# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: demo-knowledgebase
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/nolantcrook/stable-diffusion-gitops.git
#     targetRevision: HEAD
#     path: apps/knowledgebase-demo/base
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: demo-knowledgebase
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - CreateNamespace=true
