apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  project: ingress-nginx
  source:
    repoURL: https://github.com/roguewavefunction/stable-diffusion-gitops.git
    targetRevision: HEAD
    path: apps/ingress/base
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 