apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/roguewavefunction/stable-diffusion-gitops.git
    targetRevision: HEAD
    path: argocd/install
    kustomize:
      version: v4.5.7
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true