apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: invokeai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nolantcrook/stable-diffusion-gitops.git
    targetRevision: HEAD
    path: apps/invokeai_cpu/base
  destination:
    server: https://kubernetes.default.svc
    namespace: invokeai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 