apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stratis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nolantcrook/stable-diffusion-gitops.git
    targetRevision: HEAD
    path: apps/stratis/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: stratis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
