apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - secrets.yaml
  - ingress.yaml


# For production overlays, you can use secretGenerator instead of the plain secrets.yaml
# secretGenerator:
# - name: langchain-secrets
#   namespace: langchain
#   envs:
#   - .env 