apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langchain-external-secrets
  namespace: langchain
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: langchain-secrets
    creationPolicy: Owner
  data:
  - secretKey: openai-api-key
    remoteRef:
      key: langchain/openai-api-key
      property: key
  - secretKey: kaggle-username
    remoteRef:
      key: langchain/kaggle-username
      property: username
  - secretKey: kaggle-key
    remoteRef:
      key: langchain/kaggle-key
      property: key
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: langchain
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: langchain-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: langchain-sa
  namespace: langchain
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891377073036:role/langchain-role # This will be substituted during deployment 