apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
- namespace.yaml
- configmap.yaml
- rbac.yaml
- service.yaml
- ingressclass.yaml
- ingress-rules/argocd-ingress-rules.yaml
- ingress-rules/stable-diffusion-ingress-rules.yaml
