apiVersion: apps/v1
kind: Deployment
metadata:
  name: invokeai-deployment
  namespace: invokeai
  labels:
    app: invokeai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invokeai
  template:
    metadata:
      labels:
        app: invokeai
    spec:
      nodeSelector:
        node.kubernetes.io/gpu: "true"
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: invokeai
        image: mauwii/invokeai:latest
        ports:
        - containerPort: 9090
        command: ["invokeai"]
        args: ["--web", "--host", "0.0.0.0", "--port", "9090","--cors", "https://invokeai.hello-world-domain.com"]
        env:
        - name: USE_CPU
          value: "false" # Example environment variable to force CPU usage
        - name: CUDA_MPS_PIPE_DIRECTORY
          value: "/tmp/nvidia-mps" # Same as MPS control daemon
        - name: CUDA_MPS_LOG_DIRECTORY
          value: "/tmp/nvidia-log" # Same as MPS control daemon
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
            ephemeral-storage: "2Gi" # Requesting 2 GiB of ephemeral storage
            nvidia.com/gpu: "1" # Requesting 1 GPU
          limits:
            memory: "8Gi"
            cpu: "2"
            ephemeral-storage: "4Gi" # Limiting to 4 GiB of ephemeral storage
            nvidia.com/gpu: "1" # Limiting to 1 GPU

