apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: invokeai
  namespace: invokeai
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: "https://invokeai.hello-world-domain.com/oauth2/idpresponse"
    nginx.ingress.kubernetes.io/auth-signin: "https://invokeai.hello-world-domain.com/oauth2/idpresponse"
spec:
  rules:
  - host: invokeai.hello-world-domain.com
    http:
      paths:
      - path: /oauth2/idpresponse
        pathType: Prefix
        backend:
          service:
            name: invokeai
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: invokeai
            port:
              number: 80
