apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invokeai

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- storageclass.yaml
- pvc.yaml
- persistent-volume.yaml
- service-account.yaml
