apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invokeai

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- nvidia-smi.yaml
- mps-daemonset.yaml
- storageclass.yaml
- pvc.yaml