apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi
  namespace: invokeai
spec:
  restartPolicy: OnFailure
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  containers:
  - name: nvidia-smi
    image: nvidia/cuda:12.5.0-runtime-ubuntu20.04
    args:
    - "nvidia-smi"
    env:
    - name: CUDA_MPS_PIPE_DIRECTORY
      value: "/tmp/nvidia-mps" # Same as MPS control daemon
    - name: CUDA_MPS_LOG_DIRECTORY
      value: "/tmp/nvidia-log" # Same as MPS control daemon
    resources:
      limits:
        nvidia.com/gpu: 1
