apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi
  namespace: invokeai
spec:
  restartPolicy: OnFailure
  containers:
  - name: nvidia-smi
    image: nvidia/cuda:12.5-runtime-ubuntu20.04
    args:
    - "nvidia-smi"
    resources:
      limits:
        nvidia.com/gpu: 1